### ISSUE TITLE
Proposal for less intrusion on other actions

### ISSUE THREAD

**Issue by Sephi-Chan** [ndhays/redux-cablecar#1]
Hi!

I tried cablecar with some success (regarding the server push) but I find quite intrusive to set `CableCar: false` on **every** other action object.

Perhaps using a CableCar: true for CableCar messages or prefixing the action type with "CABLECAR_" would do the job.

What do you think?

Thanks for cablecar!

**Comment by ndhays** [comment]
@Sephi-Chan thanks that's a great idea! I made some changes and pushed up a new version.

Now you can set a prefix for action types w/ 'CABLECAR' used as the default. I also added a small demo app.

Let me know what you think!
