### ISSUE TITLE
How to make it work with redux-toolkit?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [ndhays/redux-cablecar#10]
Redux-Toolkit is a widely used framework for the redux store and it expects messages in the format of:

"reducername/functionname"

See also here: https://redux-toolkit.js.org/tutorials/intermediate-tutorial#updating-the-todos-tests

On our system we are currently pushing out notifications with underscores only "reducername_functionname" and therefore redux toolkit doesn't call the corresponding reducer actions.

Is there any way to interecept and preformat the type of the notification? Or any other best practices?

**Comment by ndhays** [comment]
@h0jeZvgoxFepBQ2C - sorry to take so long to reply.

I'm not exactly sure what you are asking. The cablecar internal actions seem names appropriately b/c they don't really match up with a reducer.

I changed it to accept a list as a 'prefix' option (**version 3.0.9**), which I think could make sense.

Let me know, thanks.
