### ISSUE TITLE
incompatible with node 16.x ?

### ISSUE THREAD

**Issue by krtschmr** [ndhays/redux-cablecar#17]
![image](https://user-images.githubusercontent.com/13366714/137885817-bf723c70-075c-4c65-8c4a-71c8b0935e55.png)

**Comment by alexcameron7** [comment]
Hello, I'm also experiencing a problem with the node engine requirement. This package used to support node >=12.16.1, but we have recently upgraded to the latest release which now requires 15.x. Is it possible to still support node 14?

**Comment by krtschmr** [comment]
@alexcameron7 
you need to patch the packages engine yourself.

you can do it like this https://github.com/ndhays/redux-cablecar/pull/18/files and just specify the github url in your package.json file
