### ISSUE TITLE
Use within a webpack environment?

### ISSUE THREAD

**Issue by joshuabowers** [ndhays/redux-cablecar#2]
Do you have a suggested way to define / provide `ActionCable` to `CableCar` in a JS environment not using the asset pipeline? The current project I'm working on is making use solely of webpack in a rails 5.1 setup, with no asset pipeline bootstrapping anything. ActionCable is being provided to the setup via [yarn](https://www.npmjs.com/package/actioncable).

The solution that I got working was to edit my webpack config, like so:

```js
...
plugins: [
  ...
  new webpack.ProvidePlugin({
    ActionCable: 'actioncable'
  })
]
...
```

Is this the intended way to provide the dependency to CableCar? If so, you might want to make a note of it in the readme so that others can get their environment set up.

**Comment by ndhays** [comment]
Thanks, a late reply but I will add a note in the README.
