### ISSUE TITLE
Dependency on ActionCable as a global doesn't play well with bundlers

### ISSUE THREAD

**Issue by jasonkarns** [ndhays/redux-cablecar#5]
It's undesirable to have globals in general. And in particular makes bundling (ie, webpacker) more difficult.

https://github.com/ndhays/redux-cablecar/blob/master/src/cableCar.js#L29

I'd suggest having the ActionCable dep injected via a parameter or option somewhere so consumers of cablecar can import and provide it, rather than needing it set as a global.

Also, ActionCable should be included as a peerdep, I believe?

**Comment by ndhays** [comment]
thanks, @jasonkarns. This change has been added
