### ISSUE TITLE
Is there a way to use this outside of a rails codebase?

### ISSUE THREAD

**Issue by UnderpantsGnome** [ndhays/redux-cablecar#6]
I tried a few different things to get this to work outside of Rails and kept getting the `CableCar tried to connect to ActionCable but ActionCable is not defined` error.

Maybe I'm missing something. If not, this allows you to use the npm actioncable package as a fallback. I didn't go straight to PR since I'm guessing it's not the way you'd go about it.

https://github.com/UnderpantsGnome/redux-cablecar/commit/57522b21cd72f5f0d9fb187a60483fd71631e784

**Comment by hansololai** [comment]
yeah, if you look at the src/cablecar.js you see it's trying to access a global ActionCable object, which was auto generated by rails. So it cannot access it. 

SOLUTION
define the global variable yourself. 
You can do that with require, import etc. 
Assume you are doing something with webpacker, you can do that on your root. (just before the place you use the cablecar

import ActionCable from 'actioncable';
global.ActionCable = ActionCable;

Then where-ever you use that cable-car, it will be able to access the global object.

**Comment by hansololai** [comment]
looks like you just solved it

**Comment by hansololai** [comment]
For people don't want to fork it and make another npm package, you can simply define a global variable before importing the cablecar, somewhere in your entry js file, or the main js file by doing
global.actioncable = ...;

**Comment by ndhays** [comment]
Thanks, this is changed in v3
