### ISSUE TITLE
Remove global ActionCable requirement

### ISSUE THREAD

**Issue by ashbreeze** [ndhays/redux-cablecar#7]
Cablecar currently requires a global ActionCable variable to be set, despite it having an API to set a provider.

Update:
`this.subscription = ActionCable.createConsumer(options.wsURL).subscriptions.create(`
To:
`this.subscription = this.cableProvider.createConsumer(options.wsURL).subscriptions.create(`

https://github.com/ndhays/redux-cablecar/blob/master/src/cableCar.js#L33

**Comment by ashbreeze** [comment]
#8

**Comment by ndhays** [comment]
Thanks @ashbreeze sorry for the delay!
