### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by saadnaveed** [ndhays/redux-cablecar#9]
Hey,

Just want to say that this is an awesome piece of package, and I appreciate your work on this. It seems like there might be an issue in regards to when we set `this.running = true` here: https://github.com/ndhays/redux-cablecar/blob/master/src/cableCar.js#L37

When we dispatch the action `CABLECAR_CONNECTED` before setting `this.running = true`, then this will cause this error to popup: https://github.com/ndhays/redux-cablecar/blob/master/src/middleware.js#L37

For my use case, I'm waiting for `CABLECAR_CONNECTED` and then dispatching another action as soon as the value is set to true in my state. My fix was setting `this.running = true` before dispatching the action.

Let me know if that makes sense.

Thanks,
Saad

**Comment by saadnaveed** [comment]
@ndhays

**Comment by ndhays** [comment]
Hi @saadnaveed sorry for the delay, but thanks for this, good catch!
I switched the order and it is published in 3.0.8.
